### ISSUE TITLE
Add documentation of fetching a users profile picture

### ISSUE THREAD

**Issue by Foorack** [vrchatapi/specification#113]
Normally people should use `currentAvatarThumbnailImageUrl` when listing users, but `profilePicOverride` must be used if one is set. This should be made clear in docs.

**Comment by mzmt** [comment]
@Foorack 

As far as I can see, `currentAvatarImageUrl` too.
Not only `currentAvatarThumbnailImageUrl`.

I'll try to fix this issue!
