### ISSUE TITLE
[feature request] Add golang API library?

### ISSUE THREAD

**Issue by OptoCloud** [vrchatapi/specification#130]
Would be really nice to have a golang library as well :)

**Comment by Foorack** [comment]
Hello, thank you for the suggestion request.

Will look into it when I have time.

**Comment by McHauge** [comment]
Hi, I was wondering if this is something that's still possibly coming, or if it's more one of those things that kinda died of, while working on other stuff :)

**Comment by OptoCloud** [comment]
@McHauge PR was just merged for initial implementation here: https://github.com/vrchatapi/vrchatapi-go/pull/2
Shouldnt be too long before the implementation is functional, I don't know the specifics behind the tweaking that gets done with the generated code.
