### ISSUE TITLE
Undocumented endpoint (/pigascii)

### ISSUE THREAD

**Issue by DubyaDude** [vrchatapi/specification#146]
Originally referenced here: https://github.com/vrchatapi/vrchatapi.github.io/issues/113

[api/1/pigascii](https://vrchat.com/api/1/pigascii) returns a JSON object that contains one object 'pig' on a GET request, have not tested any other type of request.
I think this can be safely assumed as a 'meme endpoint' with no actual functionality.

Response at time of writing:
```JSON
{"pig":"\n             __,---.__\n        __,-'         `-.\n       /_ /_,'           \\&\n       _,''               \\\n      (\")            .    |\n pig   ``--|__|--..-'`.__|\n"}
```

formatted 'pig' object:
```
             __,---.__
        __,-'         `-.
       /_ /_,'           \&
       _,''               \
      (")            .    |
 pig   ``--|__|--..-'`.__|
 ```
 
 edit: fixed formatted version, @information-redacted brought up I forgot to remove some escape characters

**Comment by information-redacted** [comment]
```
             __,---.__
        __,-'         `-.
       /_ /_,'           \\&
       _,''               \\
      (\")            .    |
 pig   ``--|__|--..-'`.__|
```

(btw you're a nerd)

**Comment by ItzOnlyAnimal** [comment]
```             __,---.__
        __,-'         `-.
       /_ /_,'           \\&
       _,''               \\
      (\")            .    |
 pig   ``--|__|--..-'`.__|
```

Perhaps they'll make this some makeshift interactive endpoint that changes when you fw it :trollface:

**Comment by information-redacted** [comment]
```
             __,---.__
        __,-'         `-.
       /_ /_,'           \&
       _,''               \
      (")            .    |
 pig   ``--|__|--..-'`.__|
```

(btw to anyone wondering, you can pipe the output to `jq -r .pig` to actually get the formatted version)

**Comment by ariesclark** [comment]
```
             __,---.__
        __,-'         `-.
       /_ /_,'           \&
       _,''               \
      (")            .    |
 pig   ``--|__|--..-'`.__|
```
If someone wants to give adding the endpoint a try, 
feel free. I'll merge it if everything looks good.

**Comment by Katistic** [comment]
```
             __,---.__
        __,-'         `-.
       /_ /_,'           \&
       _,''               \
      (")            .    |
 pig   ``--|__|--..-'`.__|
```
Looks like they removed this endpoint,
damn lol

**Comment by DubyaDude** [comment]
sadge

**Comment by ItzOnlyAnimal** [comment]
rip
