### ISSUE TITLE
Undocumented Endpoint (/2/)

### ISSUE THREAD

**Issue by DubyaDude** [vrchatapi/specification#149]
[api/2/](https://api.vrchat.cloud/api/2/) (api/2 will NOT work) with anything written after will immediately redirect you to VRChat's next secret project.

This currently seems to only be available on the api.vrchat.cloud sub-domain as it's not currently re-creatable in the main vrchat.com domain.

Before I get asked 'source?' my lawyer advised me to say the following:
```
i tried checking if vrchat is making progress on giving the api an overhaul
and surely they are
```

**Comment by information-redacted** [comment]
pretty pog project if you ask me ngl

**Comment by DubyaDude** [comment]
> pretty pog project if you ask me ngl

ik, surprised they left it out in the open like that

**Comment by DubyaDude** [comment]
> I really like how they decided to improve on so many issues, yeah

here, take cat and fell better

https://user-images.githubusercontent.com/13679909/168313497-c37f77da-9818-454a-a6ea-0990da76b4b9.mp4

**Comment by Foorack** [comment]
This endpoint seem to no longer exist. It was likely removed. But thanks for the issue report. Closing as endpoint no longer exist.
