### ISSUE TITLE
Finding an API domain in the documentation is rather difficult

### ISSUE THREAD

**Issue by abbeybabbey** [vrchatapi/specification#150]
It came to my attention recently when I was searching for something in the API Docs just how **difficult it is to find the [api.vrchat.cloud/api/1](https://api.vrchat.cloud/api/1) domain for all the endpoints** (at least for the documented ones it is that). I find it rather annoying, because when I didn't want to use insomnia I was literally unable to find the domain for the endpoints mentioned anywhere in the **whole** documentation. Only way I was able to find the domain for the endpoints was downloading and opening insomnia and looking at the _base_url_ variable, which obviously forced me to do a previous step that I didn't want to do. Of course I have some ideas where to show/mention the domain. One of the places could be in https://vrchatapi.github.io/tutorials/getting-started/ in the _Welcome to the VRChat API_ maybe something like this: 
> The VRChat API can be used to programmatically retrieve or update information regarding your profile, friends, avatars, worlds and more. The API is designed around the REST ideology, providing semi-simple and usually predictable URLs to access and modify objects. This Getting Started quick-start guide is the fastest to get started using the API. The domain for all VRChat API endpoints is <a href="https://api.vrchat.cloud/api/1">api.vrchat.cloud/api/1</a>.

I would also add one more thing for people who don't bother to read _Getting Started_ and that's a lot of people from my experience, where hovering over request type (post, put, get etc) would show the domain (base URL) as well something like this:
![firefox_ZeE1JcHJ6l](https://user-images.githubusercontent.com/61197745/168943127-ae1e0b81-cc8d-4b89-a32a-a2b760445b6a.png)

Let me know your thoughts and correct me if I'm wrong about anything, but as it seems that domain is the only API domain as of now (that's documented as well).

**Comment by ariesclark** [comment]
Paid bounty (5USD).
https://app.bountysource.com/issues/109606150-finding-an-api-domain-in-the-documentation-is-rather-difficult

**Comment by Rexios80** [comment]
Wait it's worth $5 to shove the base url somewhere visible on the website?

**Comment by rakino** [comment]
Hello! I'm interested in this. How about adding code samples (e.g. for cURL) to the docs?
