### ISSUE TITLE
/users/{userId} endpoint requires apiKey in query params

### ISSUE THREAD

**Issue by Katistic** [vrchatapi/specification#160]

**Comment by Katistic** [comment]
From commit: `Might be an issue with other endpoints as well, will close issue for now`

**Comment by Foorack** [comment]
Why does it require api key in query parameter? Why can't it take it in cookie like all the others?

**Comment by Foorack** [comment]
Reverted. Just tested in Insomnia and the endpoint works fine without having to send the API key in query.
If you were using any of the SDK's, did you have the API key in cookie storage from a previous API call? (e.g. to getConfig or getCurrentUser?)

**Comment by Katistic** [comment]
getConfig and getCurrentUser were both called beforehand, so I don't know why this was just specifically an issue with me
