### ISSUE TITLE
Number vs Integer in Data Types not consistent between APIs

### ISSUE THREAD

**Issue by Foorack** [vrchatapi/specification#199]

**Comment by ariesclark** [comment]
Do these have an impact on the generated types, could be worth looking into.

**Comment by Foorack** [comment]
> Do these have an impact on the generated types, could be worth looking into.

Yes, because number can be both int and float, while integer is always int.

**Comment by C0D3-M4513R** [comment]
What is the expected resolution of this? Converting all `number` to `integer`?
