### ISSUE TITLE
No API endpoint for verifying one-time code sent via email

### ISSUE THREAD

**Issue by Datalink-Wouter** [vrchatapi/specification#218]
Hi,
This package worked perfect for me untill yesterday.
Every time I login using vrchat.AuthenticationApi it throws a "ERR_UNHANDLED_REJECTION" and I get an email from VRChat with a "one-time code".
Even with 2FA being disabled it's sending me this one-time code. 
Anyone knows if this is a bug on VRC's end?

**Comment by Rexios80** [comment]
Are you running the code locally? Using a VPN? Anything else weird?

**Comment by Datalink-Wouter** [comment]
Yeah locally, without VPN.
I'm using both twitch and discord API in the same project and those work just fine.
It's weird that it happened out of nowhere. 
Haven't changed anything in the last week and it ran fine till after an hour.
My best guess is that I maybe hit some kind of request limit and I have to use this one-time code to verify the device? (I can login on the website fine using the same device just fine)

**Comment by Rexios80** [comment]
How often are you authenticating? There are pretty harsh rate limits for auth, and you should be caching the auth cookie so you can reauth as infrequently as possible.

**Comment by Foorack** [comment]
@Rexios80 I don't think they are necessarily doing anything wrong, but this being a new security feature.

**Comment by Datalink-Wouter** [comment]
Hm, authentication only happens when initiating the program, which is is max 5 times a day.
Didn't really think about caching the auth cookie, will implement that!

**Comment by ariesclark** [comment]
Can you take a look at what the request is for verifying the email code?

**Comment by Datalink-Wouter** [comment]
I don't think verifying the one-time code is possible using the API, or I'm completely missing something. 
The auth/twofactorauth/totp/verify is for the main 2FA. 
When posting the email token to that endpoint I get a "No secret to match against codeǃ" (which makes sense because I disabled 2FA)
When posting to auth/twofactorauth/otp/verify I get a "code value <my-code> isn't a valid one-time password"

**Comment by Foorack** [comment]
This must be a new endpoint

**Comment by ariesclark** [comment]
> I don't think verifying the one-time code is possible using the API, or I'm completely missing something. The auth/twofactorauth/totp/verify is for the main 2FA. When posting the email token to that endpoint I get a "No secret to match against codeǃ" (which makes sense because I disabled 2FA) When posting to auth/twofactorauth/otp/verify I get a "code value isn't a valid one-time password"

It is certainly a look endpoint, if possible, click whatever link they gave in the email, open dev tools, and under the network tab, watch while you submit the code.

**Comment by Datalink-Wouter** [comment]
There's no link in that mail, just the one-time code.
Guess I'll wait for the team to add the endpoint to the docs

**Comment by Rexios80** [comment]
I think they meant check in the browser dev tools to see what call the website makes when you verify it

**Comment by Foorack** [comment]
@Rexios80 No I think I see what @Datalink-Wouter mean.

The email only contain a code, nothing else.
And then you ate supposed to enter it into the website or the game.

**Comment by Foorack** [comment]
And as he is triggering this from his owl code, he can't see.

I can probably figure this one out by looking at the website source. Currently in bed but will check tomorrow morning.

**Comment by Datalink-Wouter** [comment]
yup, exactly.
I could try and force the verification on the website by spamming the login form so it redirects to the verification page but I don't think that's a good idea ^^
No need to rush! Thanks for the help so far

**Comment by Rexios80** [comment]
These kind of verifications are usually for significant ip address changes, so you might be able to trigger it by using a vpn in a different country or something

**Comment by Foorack** [comment]
No that triggers a different kind of security check, asking if you want to allow login from county X.

I have heard of this one triggering naturally, maybe if your password gets a hit in HIBPwned?

**Comment by Rexios80** [comment]
Don't they just reset your password for you if that happens? Also they said they can log into the website fine right?

**Comment by Datalink-Wouter** [comment]
Using a VPN throws the same error and my password hasn't been compromised (auto generated password).
The e-mail I'm using has a ton of hits in HIBPwned though, but this password should be unique.
Also just tried changing password but same result.
And yup, I can login on the website just fine (both phone and same device the program runs on)

**Comment by Datalink-Wouter** [comment]
I did some more digging and while trying to login using a different browser I managed to find the page for entering this one-time code. 
In the network tab I found this new endpoint when submitting the form:
auth/twofactorauth/emailotp/verify

It's similar to the "Verify 2FA code" endpoint but it's used to verify this email token. 
Just simply post to that endpoint the same way as "Verify 2FA code" and it's working now
