### ISSUE TITLE
Instances: Send Self Invite no longer works

### ISSUE THREAD

**Issue by FTWGaming0** [vrchatapi/specification#250]
Discovered while using the JS library, but attempting to use curl with the format shown in the docs returns this:
`{"error":"The endpoint you're looking for is not implemented by our system.","status_code":404}`

**Invites: Invite Myself To Instance** works instead.

**Comment by jellejurre** [comment]
fixed in https://github.com/vrchatapi/specification/commit/f232e2e707c1f245975f97ebb14b183ecda01267
