### ISSUE TITLE
Current location and worldId could be "private"

### ISSUE THREAD

**Issue by ZZPot** [vrchatapi/specification#263]
https://github.com/vrchatapi/vrchatapi-python/blob/6701db0bb85531dea560103679a2a8faad2038d8/vrchatapi/models/user.py#L590
https://github.com/vrchatapi/vrchatapi-python/blob/6701db0bb85531dea560103679a2a8faad2038d8/vrchatapi/models/user.py#L863

Causes validation error

**Comment by ariesclark** [comment]
Should be fixed via #259.

**Comment by ariesclark** [comment]
Closed by #264.
