### ISSUE TITLE
Missing spec: Instance.world, instance, instance.n_users renamed to memberCount, missing /groups/:id/instances

### ISSUE THREAD

**Issue by ImLvna** [vrchatapi/specification#270]
`Instance.world` is either a world or a limitedworld, i cant tell
`Instance.n_users` has been renamed to `Instance.memberCount` as far as i can tell
`/groups/:id/instances` is missing from the spec entirely, returns either an instance or limitedinstance i havent checked

**Comment by Foorack** [comment]
@ttshivers  Thank you very much for the contributions! Minor problem, while the endpoint was added, it is missing from main `paths.yml`, so the bundler is not including it when building the final spec. Could you please make a follow-up PR for this? <3

@ariesclark We should write a CI job which checks for all paths in any of the files inside `paths/` are also included in the main `paths.yml` file. Generating the file automatically is possible but harder, as the order inside the file dictate the order on the website.
