### ISSUE TITLE
Get Group Member has a 403 Error

### ISSUE THREAD

**Issue by StarLight-Oliver** [vrchatapi/specification#350]
The end point "/groups/{groupId}/members/{userId}"
is capable of getting a 403 error when the logged in user is not in that group.

HTTP response body: {"error":{"message":"You're not a member․","status_code":403}}

**Comment by C0D3-M4513R** [comment]
I this instead:
`{"error":{"message":"You're not allowed to view membership details․","status_code":403}}`
