### ISSUE TITLE
Missing Invite API endpoints

### ISSUE THREAD

**Issue by Foorack** [vrchatapi/specification#37]
/invite
/requestInvite
Also how respond? Document

Edit: also all of the /response endpoints and ResponseSlot management

~~**Blocked**: Blocked by Message API #33~~

**Comment by TomAvecLeVdsl** [comment]
Sending an invite with a message goes like this
`

{
    "instanceId": "wrld_My-Awsome-Workd-id-abcdef2345:12345~private(usr_My-Awsome-user-id-abcd12345678~region(eu)~nonce(ABCDEFGHIJKLMNOPQRDTUVWXYZ1234)",
    "messageSlot": 11,
    "worldId": "wrld_My-Awsome-Workd-id-abcdef2345:12345~private(usr_My-Awsome-user-id-abcd12345678~region(eu)~nonce(ABCDEFGHIJKLMNOPQRDTUVWXYZ1234)",
    "worldName": "VRChat Home"
}

`

**Comment by TomAvecLeVdsl** [comment]
to send a responce to an invite you need to post to "https://api.vrchat.cloud/api/1/invite/not_an-invite-uuid-9e73-6443f8fa82eb/response" with the following body
 `
{
    "responseSlot": 0,
    "rsvp": true
}`

You will get the following body in responce 
`
{
    "created_at": "2021-09-08T23:23:49.063Z",
    "details": {
        "inResponseTo": "not_an-invite-uuid-9e73-6443f8fa82eb",
        "responseMessage": "I'm busy right now! Please ask me again later."
    },
    "id": "not_another-random-UUID-88ef-f65a074988d7",
    "message": "",
    "receiverUserId": "usr_my-second-vrchat-acc-yeswelovethat12345",
    "senderUserId": "usr_my0wn-perso-user-uuid-1234567890",
    "senderUsername": "MyAwsomeUsername",
    "type": "inviteResponse"
}
`

**Comment by Foorack** [comment]
InviteMessage editing has been implemented so this is no longer blocked. Will work on this next.

**Comment by Foorack** [comment]
This has been completed with #68 and soon be released as version 1.3.0

**Comment by Foorack** [comment]
After testing I'm pretty sure `worldName`, `worldId `and `rsvp` ddoes **nothing**.

An easy test is setting them to an incorrect type. If they are *actually* in use then VRChat API will respond with an error saying e.g. "must be integer", but it seems to completely ignore them.

**Comment by TomAvecLeVdsl** [comment]
As worldID is the same thing as InstanceID probably, i think WorldName is what is displayed in the invite, would need testing and rsvp ... yeah idk

**Comment by Foorack** [comment]
@TomAvecLeVdsl As I've said, already tested. Both worldName and worldId does **nothing**.

**Comment by TomAvecLeVdsl** [comment]
Oh okey :)

**Comment by Foorack** [comment]
I first optimistically set it to a custom name, and it didn't show up in the notification.

Secondly as mentioned above, you can try set the field to something invalid, like 0 or false, and it should throw a TypeError if it is an invalid type, but it didn't. 🙂
