### ISSUE TITLE
Missing exists endpoint

### ISSUE THREAD

**Issue by abbeybabbey** [vrchatapi/specification#72]
![alt text](https://i.imgur.com/npK07YT.png)
I'm still quite new to insomnia so I'm not really sure how to document it properly, so I've just opened an issue instead.

**Comment by Foorack** [comment]
Wow! Never heard of this. Thanks!

**Comment by abbeybabbey** [comment]
![400 Bad Request](https://i.imgur.com/xqcalz8.png)
takes in three parameters: username, email, or displayName
![200 Ok](https://i.imgur.com/jiuUv5w.png)
returns true or false if user exists
![200 Ok Exclusion](https://i.imgur.com/9c6zx0P.png)
we can exclude userId to see if anyone else with the same email, displayName or username exists 👀 
![200 Ok No limits](https://i.imgur.com/z9ppVUe.png)
![200 Ok No limits2](https://i.imgur.com/31DNOuD.png)
It seems there're no limitations to what you can search, even though vrchat itself doesn't allow it (kinda). I understand the part with blank username that it shows the user exists. As you might know euan [vrchat.com/home](https://vrchat.com/home/user/usr_efd9a3d2-aa8e-4f7d-b285-37e7b541d231) uses blank username vrc account and changes his name in game through photon set user properties, because he's an admin. Also he's not the only one with blank username and in his case he has actually two blank "spaces" in his name. There's also this person [vrchat.com/home](https://vrchat.com/home/user/usr_619eb1fe-e36d-484a-a350-f5faa2f7ccdcl) whose username is only one blank "space".
